# Generated by Django 5.2.12 on 2026-03-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("participants", "0001_initial"),
        ("trainings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "imei_1",
                    models.CharField(blank=True, max_length=20, verbose_name="IMEI 1"),
                ),
                (
                    "imei_2",
                    models.CharField(blank=True, max_length=20, verbose_name="IMEI 2"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("phone", "Phone"),
                            ("laptop", "Laptop"),
                        ],
                        default="tablet",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="participants.participant",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="common.lga",
                        verbose_name="LGA",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="common.state",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="trainings.training",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
