# Generated by Django 5.2.12 on 2026-03-24 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="condition",
            field=models.CharField(
                choices=[
                    ("good", "Working"),
                    ("faulty", "Faulty"),
                    ("not_working", "Not Working"),
                    ("unknown", "Unknown"),
                ],
                default="good",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("returned", "Returned"),
                    ("damaged", "Damaged"),
                    ("lost", "Lost"),
                    ("replaced", "Replaced"),
                    ("not_working", "Not Working"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("replaced", "Replaced"),
                            ("not_working", "Not Working"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Working"),
                            ("faulty", "Faulty"),
                            ("not_working", "Not Working"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="What happened, issue description, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
