# Generated by Django 5.2.12 on 2026-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_condition_alter_device_status_devicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="accessories_complete",
            field=models.BooleanField(
                default=True,
                help_text="Are all accessories (charger, case, etc.) present?",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional notes about this device"
            ),
        ),
    ]
