# Generated by Django 5.2.12 on 2026-03-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for roles that apply across all channels",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_roles",
                        to="common.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "channel")},
            },
        ),
    ]
