# Generated by Django 5.2.12 on 2026-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_trainingrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantcategory",
            name="default_days",
            field=models.PositiveIntegerField(
                default=1, help_text="Default number of training days for this category"
            ),
        ),
    ]
