# Generated by Django 5.2.12 on 2026-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_participantcategory_default_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mileage_rate_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=367,
                        help_text="NGN per km for road mileage (round trip auto-calculated)",
                        max_digits=10,
                    ),
                ),
                (
                    "terminal_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=30000,
                        help_text="Terminal fee per round trip for air travelers (15k × 2)",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
