# Generated by Django 5.2.12 on 2026-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_systemsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="terminal_fee",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="terminal_fee_per_leg",
            field=models.DecimalField(
                decimal_places=2,
                default=15000,
                help_text="Terminal fee per leg (house↔airport). 15k per leg, so round trip = 30k",
                max_digits=10,
            ),
        ),
    ]
