# Generated by Django 5.2.12 on 2026-03-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "cbn_code",
                    models.CharField(
                        help_text="CBN/NIP 3-digit code used by payment APIs",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "unicef_code",
                    models.CharField(
                        blank=True,
                        help_text="UNICEF internal bank code for their payment system",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active banks appear in selection lists",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=10)),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Account holder name returned by validation API",
                        max_length=200,
                    ),
                ),
                (
                    "is_proxy",
                    models.BooleanField(
                        default=False,
                        help_text="This is a colleague's account used on behalf of the participant",
                    ),
                ),
                (
                    "proxy_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the account owner if this is a proxy account",
                        max_length=200,
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "validation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nuban", "NUBAN Check-Digit"),
                            ("paystack", "Paystack API"),
                            ("flutterwave", "Flutterwave API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="banks.bank",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
