# Generated by Django 5.2.12 on 2026-03-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "channel_role",
                    models.CharField(
                        blank=True,
                        help_text="Role within their channel (e.g., State ICT, M&E Officer)",
                        max_length=100,
                    ),
                ),
                ("health_organization", models.CharField(blank=True, max_length=200)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        help_text="Where this person is traveling from",
                        max_length=200,
                    ),
                ),
                ("ward", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Home channel this person belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="common.channel",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="common.lga",
                        verbose_name="LGA",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="common.state",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
