# Generated by Django 5.2.12 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="nin",
            field=models.CharField(blank=True, max_length=11, verbose_name="NIN"),
        ),
    ]
