# Generated by Django 5.2.12 on 2026-03-25 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_participant_nin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="System login account (auto-created for device managers)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
