from django.urls import path

from . import views

urlpatterns = [
    # Events
    path("events/", views.event_list, name="event_list"),
    path("events/create/", views.event_create, name="event_create"),
    path("events/<int:pk>/", views.event_detail, name="event_detail"),
    path("events/<int:pk>/edit/", views.event_edit, name="event_edit"),
    path("events/<int:pk>/manage/", views.event_manage, name="event_manage"),
    path("events/<int:pk>/search-users/", views.event_search_users, name="event_search_users"),
    path("events/<int:pk>/add-team/", views.event_add_team_member, name="event_add_team"),
    path("events/<int:pk>/remove-team/<int:member_id>/", views.event_remove_team_member, name="event_remove_team"),
    path("events/<int:pk>/update-channel/<int:channel_id>/", views.event_update_channel, name="event_update_channel"),
    path("events/<int:pk>/add-channel/", views.event_add_channel, name="event_add_channel"),
    path("events/<int:pk>/assign-state-admin/", views.event_assign_state_admin, name="event_assign_state_admin"),
    # Trainings
    path("", views.training_list, name="training_list"),
    path("create/", views.training_create, name="training_create"),
    path("<int:pk>/", views.training_detail, name="training_detail"),
    path("<int:pk>/edit/", views.training_edit, name="training_edit"),
    path("<int:pk>/delete/", views.training_delete, name="training_delete"),
    # Inline management (HTMX)
    path("<int:pk>/add-category/", views.add_category, name="training_add_category"),
    path("<int:pk>/add-cluster/", views.add_cluster, name="training_add_cluster"),
    path("category/<int:cat_id>/toggle/", views.toggle_category_registration, name="toggle_category_registration"),
    path("category/<int:cat_id>/edit/", views.edit_category, name="edit_category"),
    path("category/<int:cat_id>/delete/", views.delete_category, name="delete_category"),
    path("cluster/<int:cluster_id>/delete/", views.delete_cluster, name="delete_cluster"),
    path("cluster/<int:cluster_id>/edit/", views.edit_cluster, name="edit_cluster"),
    path("cluster/<int:cluster_id>/update-lgas/", views.update_cluster_lgas, name="update_cluster_lgas"),
    path("assignment/<int:assignment_id>/", views.assignment_detail, name="training_assignment_detail"),
    path("assignment/<int:assignment_id>/edit/", views.edit_assignment, name="training_edit_assignment"),
    path("<int:pk>/add-level/", views.add_level, name="training_add_level"),
    path("level/<int:level_id>/delete/", views.delete_level, name="delete_level"),
    path("<int:pk>/search-participants/", views.search_participants_for_training, name="training_search_participants"),
    path("<int:pk>/assign-participant/", views.assign_participant_to_training, name="training_assign_participant"),
    path("assignment/<int:assignment_id>/remove/", views.remove_assignment, name="training_remove_assignment"),
    path("assignment/<int:assignment_id>/attendance/", views.toggle_attendance, name="training_toggle_attendance"),
    path("<int:pk>/search-managers/", views.search_managers, name="training_search_managers"),
    path("<int:pk>/add-manager/", views.add_manager, name="training_add_manager"),
    path("<int:pk>/remove-manager/<int:user_id>/", views.remove_manager, name="training_remove_manager"),
    path("<int:pk>/toggle-devices/", views.toggle_devices, name="training_toggle_devices"),
    path("<int:pk>/save-settings/", views.save_training_settings, name="training_save_settings"),
    # Exports
    path("<int:pk>/export-financials/", views.training_export_financials, name="training_export_financials"),
    path("<int:pk>/export-participants/", views.training_export_participants, name="training_export_participants"),
    path("<int:pk>/export-provisioning/", views.training_export_provisioning, name="training_export_provisioning"),
    path("<int:pk>/export-devices/", views.training_export_devices, name="training_export_devices"),
    path("<int:pk>/export-bank/", views.training_export_bank, name="training_export_bank"),
    path("<int:pk>/exports/", views.training_exports_page, name="training_exports_page"),
    path("<int:pk>/export-bank-excel/", views.training_export_bank_excel, name="training_export_bank_excel"),
    path("<int:pk>/export-financials-excel/", views.training_export_financials_excel, name="training_export_financials_excel"),
    path("<int:pk>/send-edit-links/", views.send_edit_links, name="training_send_edit_links"),
    path("<int:pk>/dm/send-all/", views.dm_send_all, name="training_dm_send_all"),
    path("<int:pk>/dm/<int:participant_id>/send-login/", views.dm_send_login, name="training_dm_send_login"),
    path("<int:pk>/dm/<int:participant_id>/create-login/", views.dm_create_login, name="training_dm_create_login"),
    path("<int:pk>/dm/<int:user_id>/toggle/", views.dm_toggle, name="training_dm_toggle"),
]
