# Generated by Django 5.2.12 on 2026-03-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.CharField(
                        help_text="Venue/location where training takes place",
                        max_length=200,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "training_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of training days (used for DSA calculation)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Which channel this training is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainings",
                        to="common.channel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainings",
                        to="common.state",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Funtua, Malumfashi", max_length=200
                    ),
                ),
                (
                    "lgas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="LGAs that belong to this cluster",
                        related_name="training_clusters",
                        to="common.lga",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("training", "name")},
            },
        ),
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_training",
                    models.CharField(
                        help_text="Dynamic — e.g. Trainer, M&E Officer, ALGON Focal, Health Registrar, Driver",
                        max_length=100,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="DSA category for payment calculation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="common.participantcategory",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_assignments",
                        to="participants.participant",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="trainings.training",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which cluster this person belongs to in this training",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="trainings.trainingcluster",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "cluster__name",
                    "role_in_training",
                    "participant__last_name",
                ],
                "unique_together": {("training", "participant")},
            },
        ),
    ]
