# Generated by Django 5.2.12 on 2026-03-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_trainingrole"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingassignment",
            options={
                "ordering": ["cluster__name", "role__name", "participant__last_name"]
            },
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="role_in_training",
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role in this training (e.g. Trainer, M&E Officer, ALGON Focal)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="common.trainingrole",
            ),
        ),
    ]
