# Generated by Django 5.2.12 on 2026-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0002_alter_trainingassignment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="implementing_partner",
            field=models.CharField(
                blank=True, help_text="e.g. NPC HQ Abuja", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="responsible_officer",
            field=models.CharField(
                blank=True, help_text="Responsible programme officer(s)", max_length=300
            ),
        ),
    ]
