# Generated by Django 5.2.12 on 2026-03-24 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_participantcategory_default_days"),
        ("trainings", "0003_training_implementing_partner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingassignment",
            options={
                "ordering": [
                    "training_category__name",
                    "cluster__name",
                    "participant__last_name",
                ]
            },
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="category",
        ),
        migrations.AlterField(
            model_name="training",
            name="training_days",
            field=models.PositiveIntegerField(
                default=1, help_text="Total event duration in days"
            ),
        ),
        migrations.AlterField(
            model_name="trainingassignment",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="trainings.trainingcluster",
            ),
        ),
        migrations.AlterField(
            model_name="trainingassignment",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="common.trainingrole",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. TOT Trainer, LGA Trainee, Driver",
                        max_length=200,
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="DSA rate per day in NGN for this category",
                        max_digits=12,
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of days this category participates"
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("training", "name")},
            },
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="training_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category determines DSA rate and days",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="trainings.trainingcategory",
            ),
        ),
    ]
