# Generated by Django 5.2.12 on 2026-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0004_alter_trainingassignment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcategory",
            name="registration_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="Registration link expires at this date/time. Leave blank for no expiry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="registration_open",
            field=models.BooleanField(default=True),
        ),
    ]
