# Generated by Django 5.2.12 on 2026-03-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_participantcategory_default_days"),
        ("trainings", "0005_trainingcategory_registration_expires_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingassignment",
            options={"ordering": ["training_category__name", "participant__last_name"]},
        ),
        migrations.RemoveField(
            model_name="trainingcategory",
            name="daily_rate",
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="air_ticket_claim",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Air ticket amount claimed by participant",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="air_ticket_uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="origin_state",
            field=models.ForeignKey(
                blank=True,
                help_text="State traveling from (for mileage calc)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="road_mileage_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Auto-calculated road mileage cost",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="travel_mode",
            field=models.CharField(
                choices=[("none", "No Travel"), ("road", "Road"), ("air", "Air")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="dsa_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="DSA per day in NGN",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="local_transport",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Local transport allowance (flat)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="terminals",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Terminal fees (auto-added for air travelers)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="travel_mode",
            field=models.CharField(
                choices=[
                    ("none", "No Travel"),
                    ("road", "Road (Auto-Mileage)"),
                    ("air", "Air (Claim-Based)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trainings",
                to="common.channel",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="destination",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="training",
            name="implementing_partner",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="training",
            name="responsible_officer",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="training",
            name="training_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="trainingassignment",
            name="training_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="trainings.trainingcategory",
            ),
        ),
        migrations.AlterField(
            model_name="trainingcategory",
            name="days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="trainingcategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="trainingcategory",
            name="registration_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcluster",
            name="lgas",
            field=models.ManyToManyField(
                blank=True, related_name="training_clusters", to="common.lga"
            ),
        ),
        migrations.AlterField(
            model_name="trainingcluster",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
