# Generated by Django 5.2.12 on 2026-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0006_alter_trainingassignment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingcategory",
            name="terminals",
        ),
    ]
