# Generated by Django 5.2.12 on 2026-03-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_systemsettings"),
        ("trainings", "0007_remove_trainingcategory_terminals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingassignment",
            name="air_ticket_claim",
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="air_ticket_uploaded",
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="origin_state",
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="road_mileage_amount",
        ),
        migrations.RemoveField(
            model_name="trainingassignment",
            name="travel_mode",
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_air_claim",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_mileage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_mode",
            field=models.CharField(
                choices=[("none", "No Travel"), ("road", "Road"), ("air", "Air")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_air_claim",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_mileage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_mode",
            field=models.CharField(
                choices=[("none", "No Travel"), ("road", "Road"), ("air", "Air")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.state",
            ),
        ),
    ]
