# Generated by Django 5.2.12 on 2026-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0008_remove_trainingassignment_air_ticket_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="device_management",
            field=models.BooleanField(
                default=False, help_text="Enable device tracking for this training"
            ),
        ),
    ]
