# Generated by Django 5.2.12 on 2026-03-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0009_training_device_management"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingcategory",
            options={"ordering": ["level__order", "name"]},
        ),
        migrations.CreateModel(
            name="TrainingLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. State Level, LGA Level", max_length=200
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("training", "name")},
            },
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="Which training level this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="trainings.traininglevel",
            ),
        ),
    ]
