# Generated by Django 5.2.12 on 2026-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0010_alter_trainingcategory_options_traininglevel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingcategory",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="trainingcategory",
            name="level",
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which training level(s) this category participates in",
                related_name="categories",
                to="trainings.traininglevel",
            ),
        ),
    ]
