# Generated by Django 5.2.12 on 2026-03-24 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0011_alter_trainingcategory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can manage this training",
                related_name="managed_trainings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
