# Generated by Django 5.2.12 on 2026-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0012_training_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglevel",
            name="days",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of training days at this level"
            ),
        ),
    ]
