# Generated by Django 5.2.12 on 2026-03-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0013_traininglevel_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingcategory",
            name="days",
        ),
    ]
