# Generated by Django 5.2.12 on 2026-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0014_remove_trainingcategory_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcategory",
            name="arrival_day",
            field=models.BooleanField(
                default=False,
                help_text="Add 1 extra DSA day for arrival (day before training)",
            ),
        ),
    ]
