# Generated by Django 5.2.12 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0015_trainingcategory_arrival_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcategory",
            name="collect_nin",
            field=models.BooleanField(
                default=False, help_text="Require NIN during registration"
            ),
        ),
    ]
