# Generated by Django 5.2.12 on 2026-03-24 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0016_trainingcategory_collect_nin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="device_managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can manage devices for this training",
                related_name="device_managed_trainings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
