# Generated by Django 5.2.12 on 2026-03-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0017_training_device_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="device_managers",
        ),
        migrations.AddField(
            model_name="trainingcategory",
            name="is_device_manager",
            field=models.BooleanField(
                default=False,
                help_text="People in this category can manage devices for this training",
            ),
        ),
    ]
