# Generated by Django 5.2.12 on 2026-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0018_remove_training_device_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcluster",
            name="training_centre",
            field=models.CharField(
                blank=True, help_text="Venue/location for this cluster", max_length=300
            ),
        ),
    ]
