# Generated by Django 5.2.12 on 2026-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0019_trainingcluster_training_centre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcategory",
            name="travel_mode",
            field=models.CharField(
                choices=[("none", "No Travel"), ("enabled", "Travel Enabled")],
                default="none",
                max_length=10,
            ),
        ),
    ]
