# Generated by Django 5.2.12 on 2026-03-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0021_add_attendance_and_shortcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcategory",
            name="device_target_category",
            field=models.ForeignKey(
                blank=True,
                help_text="When assigning devices, only show participants from this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_by_categories",
                to="trainings.trainingcategory",
            ),
        ),
    ]
