# Generated by Django 5.2.12 on 2026-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0022_add_device_target_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_airline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="outbound_ticket",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_airline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="return_ticket",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
