# Generated by Django 5.2.12 on 2026-03-26 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_remove_systemsettings_terminal_fee_and_more"),
        ("trainings", "0023_add_airline_and_tickets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcategory",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Override channel (defaults to training's channel if blank)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="training_categories",
                to="common.channel",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("monitoring", "Monitoring"),
                            ("workshop", "Workshop/Meeting"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("implementing_partner", models.CharField(blank=True, max_length=300)),
                ("responsible_officer", models.CharField(blank=True, max_length=300)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="common.state"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="training",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent event (null for legacy trainings)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="trainings.event",
            ),
        ),
        migrations.CreateModel(
            name="EventChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_section",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Field Office, CP Section",
                        max_length=200,
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        blank=True,
                        help_text="Fallback name if responsible person has no user account",
                        max_length=200,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_channels",
                        to="common.channel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_channels",
                        to="trainings.event",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_event_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["channel__name"],
                "unique_together": {("event", "channel")},
            },
        ),
    ]
