# Generated by Django 5.2.12 on 2026-03-26 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0024_add_event_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="global_responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="Overall person responsible for this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="globally_responsible_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventchannel",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Primary payment channel for this event"
            ),
        ),
    ]
