# Generated by Django 5.2.12 on 2026-03-27 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0025_add_global_responsible_and_primary_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventchannel",
            name="implementing_partner",
            field=models.CharField(
                blank=True,
                help_text="Organization paying for this channel (e.g. NPC HQ ABUJA)",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("closed", "Closed/Disbursed"),
                    ("cancelled", "Cancelled"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Output Lead"), ("support", "Support Team")],
                        default="support",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="trainings.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "user__first_name"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
